<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 --t --transform gear.glb
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { figureColor } from '$lib/state';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Base: THREE.Mesh;
			Base_Cap: THREE.Mesh;
			C_Clamp1: THREE.Mesh;
			C_Clamp2: THREE.Mesh;
			C_Clamp3: THREE.Mesh;
			Planet_Gear: THREE.Mesh;
			Planet_Gear001: THREE.Mesh;
			Planet_Gear002: THREE.Mesh;
			Planet_Gear_Carrier: THREE.Mesh;
			Planet_Gear_Carrier_Handle: THREE.Mesh;
			Planet_Gear_Carrier_Rod: THREE.Mesh;
			Ring_Gear: THREE.Mesh;
			Ring_Gear_Handle: THREE.Mesh;
			Sun_Gear: THREE.Mesh;
			Sun_Gear_Handle: THREE.Mesh;
		};
		materials: {
			Material: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/gear-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		{#if $figureColor}
			{#key $figureColor}
				<T.Mesh
					geometry={gltf.nodes.Base.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}
				>
					<T.MeshPhysicalMaterial color={$figureColor} />
				</T.Mesh>
				<T.Mesh
					geometry={gltf.nodes.Base_Cap.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}
				>
					<T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.C_Clamp1.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.C_Clamp2.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.C_Clamp3.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear.geometry}
					material={gltf.materials.Material}
					position={[8.52, 65.9, 12.68]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear001.geometry}
					material={gltf.materials.Material}
					position={[11.83, 64, 12.68]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear002.geometry}
					material={gltf.materials.Material}
					position={[8.52, 62.09, 12.68]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear_Carrier.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear_Carrier_Handle.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Planet_Gear_Carrier_Rod.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Ring_Gear.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Ring_Gear_Handle.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Sun_Gear.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
				<T.Mesh
					geometry={gltf.nodes.Sun_Gear_Handle.geometry}
					material={gltf.materials.Material}
					position={[9.62, 63.99, 12.68]}
					scale={0.08}><T.MeshPhysicalMaterial color={$figureColor} /></T.Mesh
				>
			{/key}
		{:else}
			<T.Mesh
				geometry={gltf.nodes.Base.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			>
				<T.MeshPhysicalMaterial color={$figureColor} />
			</T.Mesh>
			<T.Mesh
				geometry={gltf.nodes.Base_Cap.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.C_Clamp1.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.C_Clamp2.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.C_Clamp3.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear.geometry}
				material={gltf.materials.Material}
				position={[8.52, 65.9, 12.68]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear001.geometry}
				material={gltf.materials.Material}
				position={[11.83, 64, 12.68]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear002.geometry}
				material={gltf.materials.Material}
				position={[8.52, 62.09, 12.68]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear_Carrier.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear_Carrier_Handle.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Planet_Gear_Carrier_Rod.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Ring_Gear.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Ring_Gear_Handle.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Sun_Gear.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
			<T.Mesh
				geometry={gltf.nodes.Sun_Gear_Handle.geometry}
				material={gltf.materials.Material}
				position={[9.62, 63.99, 12.68]}
				scale={0.08}
			/>
		{/if}
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
